<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/protobuf/any.proto

namespace GPBMetadata\Google\Protobuf;

class Any
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
Ô
google/protobuf/any.protogoogle.protobufbproto3"&
Any
type_url (	
value (BvP
com.google.protobufBAnyProtoZ,google.golang.org/protobuf/types/known/anypb¢GPBªGoogle.Protobuf.WellKnownTypes'
        , true);

        static::$is_initialized = true;
    }
}

