<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/protobuf/api.proto

namespace GPBMetadata\Google\Protobuf;

class Api
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Protobuf\SourceContext::initOnce();
        \GPBMetadata\Google\Protobuf\Type::initOnce();
        $pool->internalAddGeneratedFile(
            '
…
google/protobuf/api.protogoogle.protobufgoogle/protobuf/type.protobproto3"Å
Api
name (	(
methods2.google.protobuf.Method ((
options2.google.protobuf.Option (
version (	6
source_context2.google.protobuf.SourceContext (&
mixins2.google.protobuf.Mixin (\'
syntax2.google.protobuf.Syntax ("’
Method
name (	
request_type_url (	
request_streaming (
response_type_url (	
response_streaming ((
options2.google.protobuf.Option (\'
syntax2.google.protobuf.Syntax ("#
Mixin
name (	
root (	BvP
com.google.protobufBApiProtoZ,google.golang.org/protobuf/types/known/apipb¢GPB™Google.Protobuf.WellKnownTypes'
        , true);

        static::$is_initialized = true;
    }
}

