<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/protobuf/field_mask.proto

namespace GPBMetadata\Google\Protobuf;

class FieldMask
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
ß
 google/protobuf/field_mask.protogoogle.protobufbproto3"
	FieldMask
paths (	B…Pø
com.google.protobufBFieldMaskProtoZ2google.golang.org/protobuf/types/known/fieldmaskpb¢GPBªGoogle.Protobuf.WellKnownTypes'
        , true);

        static::$is_initialized = true;
    }
}

