<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/protobuf/empty.proto

namespace GPBMetadata\Google\Protobuf;

class GPBEmpty
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
¾
google/protobuf/empty.protogoogle.protobufbproto3"
EmptyB}Pø
com.google.protobufB
EmptyProtoZ.google.golang.org/protobuf/types/known/emptypb¢GPBªGoogle.Protobuf.WellKnownTypes'
        , true);

        static::$is_initialized = true;
    }
}

