<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/protobuf/timestamp.proto

namespace GPBMetadata\Google\Protobuf;

class Timestamp
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
ï
google/protobuf/timestamp.protogoogle.protobufbproto3"+
	Timestamp
seconds (
nanos (B…Pø
com.google.protobufBTimestampProtoZ2google.golang.org/protobuf/types/known/timestamppb¢GPBªGoogle.Protobuf.WellKnownTypes'
        , true);

        static::$is_initialized = true;
    }
}

